# Generated by Django 6.0 on 2025-12-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriterecipe",
            name="ingredients",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="favoriterecipe",
            name="steps",
            field=models.TextField(default="[]"),
        ),
    ]
